version: '3.8'

services:
  node1:
    container_name: node1
    image: bitcoinsv/bitcoin-sv:1.0.7
    expose:
      - "18332"
      - "18333"
      - "28332"
    ports:
      - "18332:18332"
      - "28332:28332"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "/entrypoint.sh", "bitcoin-cli", "getinfo" ]
    volumes:
      - ./sv/bitcoin.conf:/data/bitcoin.conf

  explorer:
    container_name: explorer
    build: ./explorer
    environment:
      PORT: "8080"
    expose:
      - "8080"
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on: 
      - node1

  dash:
    container_name: dash
    build: ./dash
    environment:
      DASH_PORT: 3000
      SV_HOST: node1
      SV_PORT: 18332
      SV_USER: bitcoin
      SV_PASSWORD: bitcoin
    ports:
      - "3010:3000"
    restart: unless-stopped
    depends_on:
      - node1

  mapi:
    container_name: mapi
    image: bitcoinsv/mapi:1.1.0
    environment:
      - httpAddress=:9004
      - bitcoin_1_host=node1
      - bitcoin_1_port=18332
      - bitcoin_1_username=bitcoin
      - bitcoin_1_password=bitcoin
      - minerId_URL=http://minerid:9002/minerid
      - minerId_alias=testMiner
    ports:
      - "9014:9004"
    restart: unless-stopped
    depends_on:
      - node1

  minerid:
    container_name: minerid
    image: bitcoinsv/minerid:1.1.1
    environment:
      NODE_CONFIG: '{
        "bitcoin": {
        "rpcHost":"node1"
        },
        "network": "regtest"
        }'
    ports:
      - "9012:9002"
    restart: unless-stopped
    depends_on:
      - node1
    volumes:
      - minerid:/root/.keystore
      - minerid:/root/.minerid-client

volumes:
  minerid:
    external: false
