version: '3.8'

services:
  node1:
    container_name: node1
    build:
      context: ./sv
      args:
        VERSION: "1.0.6"
    expose:
      - "18332"
      - "18333"
      - "28332"
    ports:
      - "18332"
      - "28332"
    restart: unless-stopped
    volumes:
      - ./sv/bitcoin.conf:/root/.bitcoin/bitcoin.conf
    networks:
      - regtest_stack

  explorer:
    container_name: explorer
    build: ./explorer
    environment:
      PORT: "8080"
    expose:
      - "8080"
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on: 
      - node1
    networks:
      - regtest_stack

  dash:
    container_name: dash
    build: ./dash
    environment:
      DASH_PORT: 3000
      SV_HOST: node1
      SV_PORT: 18332
      SV_USER: rpc
      SV_PASSWORD: rpc
    ports:
      - "3010:3000"
    restart: unless-stopped
    depends_on:
      - node1
    networks:
      - regtest_stack

  mapi:
    container_name: mapi
    image: bitcoinsv/mapi:1.1.0
    environment:
      - httpAddress=:9014
      - bitcoin_1_host=node1
      - bitcoin_1_port=18332
      - bitcoin_1_username=rpc
      - bitcoin_1_password=rpc
      - minerId_URL=http://host.docker.internal:9012/minerid
      - minerId_alias=testMiner
    ports:
      - "9014"
    restart: unless-stopped
    depends_on:
      - node1
    networks:
      - regtest_stack

  minerid:
    container_name: minerid
    image: bitcoinsv/minerid:1.1.1
    environment:
      - NODE_CONFIG='{"bitcoin":{"rpcHost":"host.docker.internal"}}'
    ports:
      - "9012"
    depends_on:
      - node1
    networks:
      - regtest_stack

networks:
  regtest_stack:
    external: true
