version: '3'
services:

  sv:
    build:
      context: ./sv
      args:
        VERSION: "1.0.6"
    networks:
    - sv
    # for debug only
    - edge
    expose:
    - "8332"
    - "8333"
    - "28332"
    ports:
    # for debug only
    - "8332:8332"
    # for debug only
    - "28332:28332"
    restart: unless-stopped
    volumes:
    - ./sv/bitcoin.conf:/root/.bitcoin/bitcoin.conf

  explorer:
    build: ./explorer
    networks:
    - sv
    - edge
    environment:
      PORT: "8080"
    expose:
    - "8080"
    ports:
    - "8080:8080"
    restart: unless-stopped
    depends_on: 
    - sv

  dash:
    build: ./dash
    environment:
      DASH_PORT: 3000
      SV_HOST: sv
      SV_PORT: 8332
      SV_USER: rpc
      SV_PASSWORD: rpc
    networks:
    - sv
    - edge
    ports:
    - "3010:3000"
    restart: unless-stopped
    depends_on:
    - sv


networks:
  sv:
    internal: true

  edge:
    driver: bridge